# Generated by Django 3.0.2 on 2020-04-23 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Protein',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unp_id', models.CharField(max_length=10)),
                ('length', models.IntegerField()),
                ('domain_num', models.IntegerField()),
                ('domain', models.CharField(max_length=50)),
            ],
        ),
    ]
